name: study_platform
description: "Flutter写的学习平台"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 7.0.0
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.0.0 
  test: ^1.24.0
  synchronized: ^3.4.0
  logging: ^1.2.0
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
